export class ResItem{
  num: number;
  name: string;
  date: string;
  id: string;
  idTotal: number;
  idNum: number;
  anchors: any;
  content: string;
  isAdded: boolean;
  parent: number;
  show: boolean;
  select: boolean;
  candi1: boolean;
  candi2: boolean;
  resColor: string;
  resFontSize: string;
  resSelect: string;
  resBackgroundColor = 'transparent';
  idBackgroundColor = '#fff';
  idColor = '#000';
  idClassNoSelect = '';
  hasImage = false;
  isFiltered = false;
  originalIndex: number;
  anchorCount: number;
  isEdit: boolean;
  resMenu: number;
  isMenuOpen: boolean;
  isRemark: boolean;
}
